user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

custom_login:
    path: /login/check-custom

github_login:
    path: /login/check-github

## Admin Login Form
#fos_admin_user_security_login:
#    path:  admin/login
#    defaults: { _controller: FOSUserBundle:Security:login }
#
## Admin Login Verification
#fos_admin_user_security_check:
#    path:  admin/login_check
#    defaults: { _controller: FOSUserBundle:Security:check }
#    requirements:
#        method: POST
#
## Logout Admin
#fos_admin_user_security_logout:
#    pattern:  admin/logout
#    defaults: { _controller: FOSUserBundle:Security:logout }