services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    my.custom.user_provider:
            class: AppBundle\Security\FOSUBUserProvider
            arguments: ["@fos_user.user_manager" ,{facebook: facebook_id}]